[versions]
agp = "8.13.2"
assertj = "3.27.7"
detekt = "2.0.0-alpha.6"
dokka = "2.2.0"
jackson = "3.2.1" # pin it
jspecify = "1.0.1"
junit = "6.1.3"
junit-pioneer = "2.3.0"
koog = "1.1.1"
kotest = "6.2.4"
kotlin = "2.4.10"
knit = "0.5.1"
kotlinxSerialization = "1.8.1"
kover = "0.9.9"
ksp = "2.3.11"
langchain4j = "1.18.1"
logging = "8.0.4"
mockk = "1.14.11"
slf4j = "2.0.18"
vanniktechMavenPublish = "0.37.0"
json-unit-assertj = "6.2.0"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
gradle-maven-publish-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "vanniktechMavenPublish" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations" }
jackson-bom = { module = "tools.jackson:jackson-bom", version.ref = "jackson" }
jackson-databind = { module = "tools.jackson.core:jackson-databind" }
json-unit-assertj = { module = "net.javacrumbs.json-unit:json-unit-assertj", version.ref = "json-unit-assertj" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junit-pioneer = { module = "org.junit-pioneer:junit-pioneer", version.ref = "junit-pioneer" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
koog-agents-tools = { module = "ai.koog:agents-tools", version.ref = "koog" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-json = { module = "io.kotest:kotest-assertions-json", version.ref = "kotest" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version.ref = "logging" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
langchain4j-core = { module = "dev.langchain4j:langchain4j-core", version.ref = "langchain4j" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }

ksp-symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
ksp-symbol-processing-aa-embeddable = { module = "com.google.devtools.ksp:symbol-processing-aa-embeddable", version.ref = "ksp" }
ksp-symbol-processing-common-deps = { module = "com.google.devtools.ksp:symbol-processing-common-deps", version.ref = "ksp" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
knit = { id = "org.jetbrains.kotlinx.knit", version.ref = "knit" }