package kotlinx.schema.generator.reflect

import kotlinx.schema.generator.core.InternalSchemaGeneratorApi
import kotlinx.schema.generator.core.ir.Introspections
import kotlinx.schema.generator.core.ir.TypeRef
import kotlin.reflect.KClass
import kotlin.reflect.KFunction
import kotlin.reflect.KProperty
import kotlin.reflect.KType
import kotlin.reflect.KVisibility
import kotlin.reflect.full.allSuperclasses
import kotlin.reflect.full.primaryConstructor
import kotlin.reflect.jvm.javaMethod
import kotlin.reflect.jvm.kotlinFunction

/**
 * Gets the [KType.classifier], ensuring it is a [KClass].
 */
internal val KType.klass: KClass<*>
    get() {
        return requireNotNull(classifier as? KClass<*>) {
            "Unsupported classifier: $classifier. " +
                "Only KClass classifiers are supported. Type parameters and other classifiers " +
                "cannot be introspected using reflection."
        }
    }

/**
 * Finds a property in a class by name.
 * Used when extracting metadata from constructor parameters to find corresponding property annotations.
 *
 * @param klass The class to search in
 * @param propertyName The name of the property to find
 * @return The property if found, null otherwise
 */
internal fun findPropertyByName(
    klass: KClass<*>,
    propertyName: String,
): KProperty<*>? =
    klass.members
        .filterIsInstance<KProperty<*>>()
        .firstOrNull { it.name == propertyName }

/**
 * Checks whether the given list of annotations contains a recognized ignore marker
 * (e.g., `@SchemaIgnore`, `@SerialSchemaIgnore`, `@JsonIgnoreType`).
 *
 * @see [Introspections.isIgnoreAnnotation]
 */
internal fun isSchemaIgnored(annotations: List<Annotation>): Boolean =
    annotations.any { annotation ->
        val javaClass = annotation.annotationClass.java
        Introspections.isIgnoreAnnotation(javaClass.simpleName, javaClass.name)
    }

/**
 * Extracts description from annotations.
 *
 * @see [Introspections.getDescriptionFromAnnotation]
 */
internal fun extractDescription(annotations: List<Annotation>): String? =
    annotations.firstNotNullOfOrNull { annotation ->
        val javaClass = annotation.annotationClass.java
        Introspections.getDescriptionFromAnnotation(
            javaClass.simpleName,
            javaClass.name,
            buildAnnotationArgs(annotation),
        )
    }

/**
 * Extracts a name override from annotations (e.g., from `@SerialName`).
 *
 * @see [Introspections.getNameOverride]
 */
@InternalSchemaGeneratorApi
public fun extractNameOverride(annotations: List<Annotation>): String? =
    annotations.firstNotNullOfOrNull { annotation ->
        val javaClass = annotation.annotationClass.java
        Introspections.getNameOverride(javaClass.simpleName, javaClass.name, buildAnnotationArgs(annotation))
    }

/**
 * Builds key-value pairs from an annotation's elements for use with [Introspections] methods.
 *
 * Uses Java reflection via [Class.getDeclaredMethods] to reliably access annotation elements,
 * including annotations from external modules where Kotlin reflection metadata may be unavailable.
 */
private fun buildAnnotationArgs(annotation: Annotation): List<Pair<String, Any?>> =
    buildList {
        annotation.annotationClass.java.declaredMethods
            .filter { it.parameterCount == 0 }
            .forEach { method ->
                val value =
                    try {
                        method.isAccessible = true
                        method.invoke(annotation)
                    } catch (_: ReflectiveOperationException) {
                        return@forEach
                    } catch (_: SecurityException) {
                        return@forEach
                    }
                add(method.name to value)
            }
    }

/**
 * Returns a new [TypeRef] with the specified nullable flag.
 */
internal fun TypeRef.withNullable(nullable: Boolean): TypeRef =
    when (this) {
        is TypeRef.Inline -> copy(nullable = nullable)
        is TypeRef.Ref -> copy(nullable = nullable)
    }

/**
 * Finds effective primary constructor of a class, filtering synthetic constructors generated by kotlinx.serialization.
 */
internal fun findPrimaryConstructor(klass: KClass<*>): KFunction<Any>? {
    /**
     * Check if this is a kotlinx.serialization generated synthetic constructor
     * with a SerializationConstructorMarker param.
     */
    fun KFunction<Any>.isSyntheticSerializationConstructor(): Boolean =
        parameters.any { param ->
            (param.type.classifier as? KClass<*>)?.qualifiedName ==
                "kotlinx.serialization.internal.SerializationConstructorMarker"
        }

    val constructor =
        klass.primaryConstructor
            ?: klass.constructors
                .filterNot { it.visibility == KVisibility.PRIVATE }
                .firstOrNull() // If no primary defined, fallback to the first one
            ?: return null

    return if (constructor.isSyntheticSerializationConstructor()) {
        // Find the real constructor without the SerializationConstructorMarker param
        klass.constructors
            .filterNot { it.visibility == KVisibility.PRIVATE }
            .firstOrNull { ctor -> ctor != constructor && !ctor.isSyntheticSerializationConstructor() }
    } else {
        constructor
    }
}

/**
 * Retrieves a list of methods that are implemented by the current function within its class hierarchy.
 */
internal fun KFunction<*>.findImplementedMethods(): List<KFunction<*>> {
    val javaMethod = this.javaMethod ?: return emptyList()
    val methodName = javaMethod.name
    val parameterTypes = javaMethod.parameterTypes

    return javaMethod.declaringClass.kotlin.allSuperclasses
        .toList()
        .mapNotNull { superclass ->
            try {
                @Suppress("SpreadOperator")
                superclass.java
                    .getDeclaredMethod(methodName, *parameterTypes)
                    .kotlinFunction
                    ?.takeIf { it != this }
            } catch (_: NoSuchMethodException) {
                null
            }
        }
}
