@file:JvmName("ReflectionUtils")

package me.kpavlov.kt.schema.generator.reflect

import kotlin.reflect.KClass
import kotlin.reflect.KFunction
import kotlin.reflect.KProperty
import kotlin.reflect.KType
import kotlin.reflect.KVisibility
import kotlin.reflect.full.allSuperclasses
import kotlin.reflect.full.primaryConstructor
import kotlin.reflect.jvm.javaField
import kotlin.reflect.jvm.javaMethod
import kotlin.reflect.jvm.kotlinFunction

/**
 * Gets the [KType.classifier], ensuring it is a [KClass].
 */
internal val KType.klass: KClass<*>
    get() {
        return requireNotNull(classifier as? KClass<*>) {
            "Unsupported classifier: $classifier. " +
                "Only KClass classifiers are supported. Type parameters and other classifiers " +
                "cannot be introspected using reflection."
        }
    }

/**
 * Finds a property in a class by name.
 * Used when extracting metadata from constructor parameters to find corresponding property annotations.
 *
 * @param klass The class to search in
 * @param propertyName The name of the property to find
 * @return The property if found, null otherwise
 */
internal fun findPropertyByName(
    klass: KClass<*>,
    propertyName: String,
): KProperty<*>? =
    klass.members
        .filterIsInstance<KProperty<*>>()
        .firstOrNull { it.name == propertyName }

/**
 * Collects all annotations relevant to a property: its own annotations, its getter's,
 * and its backing Java field's.
 *
 * This covers all common use-site targets (e.g. `@property:`, `@get:`, `@field:`) so
 * annotations like `@JsonProperty` and `@JsonIgnore` are recognized regardless of
 * where the compiler places them.
 */
internal fun collectPropertyAnnotations(property: KProperty<*>): List<Annotation> =
    property.annotations +
        property.getter.annotations +
        property.javaField?.annotations.orEmpty()

/**
 * Collects all annotations relevant to a constructor property, from the constructor
 * parameter, the Kotlin property, its getter, and its backing Java field.
 *
 * This covers all common use-site targets (e.g. `@param:`, `@property:`, `@get:`,
 * `@field:`) so annotations like `@JsonProperty` and `@JsonIgnore` are recognized
 * regardless of where the compiler places them.
 */
internal fun collectConstructorAnnotations(
    klass: KClass<*>,
    propertyName: String,
    paramAnnotations: List<Annotation>,
): List<Annotation> {
    val property = findPropertyByName(klass, propertyName)
    return paramAnnotations + property?.let(::collectPropertyAnnotations).orEmpty()
}

/**
 * Finds effective primary constructor of a class, filtering synthetic constructors generated by kotlinx.serialization.
 */
internal fun findPrimaryConstructor(klass: KClass<*>): KFunction<Any>? {
    /**
     * Check if this is a kotlinx.serialization generated synthetic constructor
     * with a SerializationConstructorMarker param.
     */
    fun KFunction<Any>.isSyntheticSerializationConstructor(): Boolean =
        parameters.any { param ->
            (param.type.classifier as? KClass<*>)?.qualifiedName ==
                "kotlinx.serialization.internal.SerializationConstructorMarker"
        }

    val constructor =
        klass.primaryConstructor
            ?: klass.constructors
                .filterNot { it.visibility == KVisibility.PRIVATE }
                .firstOrNull() // If no primary defined, fallback to the first one
            ?: return null

    return if (constructor.isSyntheticSerializationConstructor()) {
        // Find the real constructor without the SerializationConstructorMarker param
        klass.constructors
            .filterNot { it.visibility == KVisibility.PRIVATE }
            .firstOrNull { ctor -> ctor != constructor && !ctor.isSyntheticSerializationConstructor() }
    } else {
        constructor
    }
}

/**
 * Retrieves a list of methods that are implemented by the current function within its class hierarchy.
 */
internal fun KFunction<*>.findImplementedMethods(): List<KFunction<*>> {
    val javaMethod = this.javaMethod ?: return emptyList()
    val methodName = javaMethod.name
    val parameterTypes = javaMethod.parameterTypes

    return javaMethod.declaringClass.kotlin.allSuperclasses
        .toList()
        .mapNotNull { superclass ->
            try {
                @Suppress("SpreadOperator")
                superclass.java
                    .getDeclaredMethod(methodName, *parameterTypes)
                    .kotlinFunction
                    ?.takeIf { it != this }
            } catch (_: NoSuchMethodException) {
                null
            }
        }
}
