name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: temurin
  # Override version used for inter-job publishing inside CI
  CI_TEST_VERSION: 42-SNAPSHOT

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          add-job-summary-as-pr-comment: on-failure
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Build
        run: |-
          ./gradlew build \
            publishAllPublicationsToProjectRepository -Pversion=${{ env.CI_TEST_VERSION }} \
            --no-daemon

      - name: Validate README/docs snippets
        run: ./gradlew :docs:knit :docs:knitCheck --no-configuration-cache --no-daemon

      - name: Upload project repository
        uses: actions/upload-artifact@v7
        with:
          name: project-repo
          path: build/project-repo
          retention-days: 1

      - name: Upload build reports
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v7
        with:
          name: build-reports
          path: |
            **/build/reports/

      - name: Publish build test report
        uses: mikepenz/action-junit-report@v6
        if: ${{ !cancelled() }}
        with:
          report_paths: '**/test-results/**/TEST-*.xml'
          annotate_only: true
          check_name: Build Tests

  downstream:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        project:
          - name: gradle-plugin-integration-tests
            dir: gradle-plugin-integration-tests
          - name: gradle-google-ksp
            dir: examples/gradle-google-ksp

    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          add-job-summary-as-pr-comment: on-failure
          cache-read-only: true

      - name: Download project repository
        uses: actions/download-artifact@v8
        with:
          name: project-repo
          path: build/project-repo

      - name: Build ${{ matrix.project.name }}
        working-directory: ${{ matrix.project.dir }}
        run: |-
          ./gradlew clean build \
            -PkotlinxSchemaVersion=${{ env.CI_TEST_VERSION }} \
            --no-daemon

      - name: Upload reports
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.project.name }}-reports
          path: ${{ matrix.project.dir }}/**/build/reports/

      - name: Publish test report
        uses: mikepenz/action-junit-report@v6
        if: ${{ !cancelled() }}
        with:
          report_paths: '${{ matrix.project.dir }}/**/test-results/**/TEST-*.xml'
          annotate_only: true
          check_name: ${{ matrix.project.name }}
